---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - cronjob.yaml
configMapGenerator:
  - name: openbao-config
    files:
      - apply.sh
      - admins.hcl
      - external-secrets.hcl
      - config-admin.hcl
generatorOptions:
  disableNameSuffixHash: true
