---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-track-apiserver
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
