---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.8.1
    digest: sha256:c6c53f5aedf358218c0dfa421878270d31e251aa07861e32e0c142edb19b25e0
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
