---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./slo-app-availability.yaml
  - ./slo-synthetic-availability.yaml
  - ./slo-synthetic-k6-canary.yaml
