---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: erfbeeld
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/erfbeeld
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.1.0
    digest: sha256:0af2f6563565e4546b31ce0bde58e3f4cca8d7f76b17c9802c874893d2416737
