---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-offsite-metrics
spec:
  refreshInterval: "0"
  target:
    name: garage-offsite-metrics
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        username: vmagent
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator-32
