---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 85.2.0
    digest: sha256:716733f473fcfd00380cb9317c004aeb7cc8a49be311d2c28dce9f900e124491
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
