---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 85.3.0
    digest: sha256:2089b261a8af5f3217de1f1462c009f523cbc4fea86ea9b50f88d545eb773d16
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
