---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 85.3.3
    digest: sha256:469db179d6d63d43baf6237e100a0ef8c430b6aa701f15f67a3d92c4ae0ed7f6
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
