apiVersion: v1
kind: Secret
metadata:
  name: zomboid-secrets
  namespace: zomboid
type: Opaque
stringData:
  #ENC[AES256_GCM,data:49ZdUESKIsy1pFZxVZkDr50e19CILFLqD1U=,iv:or0xhk/P1RkewIfRfi0MOTBS/18lj2WdmqyzaQANpQ8=,tag:WEHXRPYG9vCt6hACxbLDEA==,type:comment]
  ADMINPASSWORD: ENC[AES256_GCM,data:KmKqS1OoamI=,iv:0e0rZK5GA6wLI9MqyB/dcxYXe9/TLX1zv8sIFJMHpK8=,tag:FZF7H37D6g1BFmAb9PBQBw==,type:str]
  #ENC[AES256_GCM,data:/NDUEwEQHHiMWsCBWBNbJDdTSdCVDeqS7jy0qJpS5cx/4g==,iv:uRp4/15zq4KlJC/c9A9RU8Li0yN7b4Ummd4DGbRyC8g=,tag:0B63yHdCtPaCnJBgd6vN1w==,type:comment]
  ADMINUSERNAME: ENC[AES256_GCM,data:jerCKrs=,iv:ApprZKrZSR58l4PUOEluq4AaeiyS07/h/ZmzWsZWERA=,tag:lOUTt4fU8rgKEhQN+O7BIQ==,type:str]
  PASSWORD: ENC[AES256_GCM,data:aQ3JysF2pUI=,iv:krGmE9Xdqbmpo2dMxNPQsbVP+1Z3SX6BrfQCyHdgGiA=,tag:+jCSEY8tfUo9dVCxu/HVlw==,type:str]
  RCONPASSWORD: ENC[AES256_GCM,data:G1E4FMoamqo=,iv:jlPIANCYgpuDy2GjGDcmX1yN8R3XQhpAPiEhpZ5nk3w=,tag:MIae4ydJAgEmAXWbAvtGgA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWEtWdVhWSTBoNEp4OXA3
        bEVPQU1RY1Z3WGExM2FYY3g2MDNGV05zZ1JnClVhTnhhdnhQZitLNzZMZjNWb2ps
        ZE15WHZKWGMwQ2ljb05FRVNqaVU3QkUKLS0tIEtCTWUwMXQ1NlNZR203dW1iSFBF
        SXhydFJUaWdYWjJYTU1ab096VEkyYk0Kd8IV5QMZqQrrVfwZyu3MSfacNMVMvkpf
        4XebAC3LuAJ32HMTQOTKulte2li44DnDmd8kpXAfIbOcCn9BO3RBCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:48:22Z"
  mac: ENC[AES256_GCM,data:rIzdEMjIkuHthvtFtJihYsEi6d08kHxwDozB61gZEpQ+rHK1NBGGO1yWAaCfqrW2yqTl+MGoz6qOCHHr8VyV+nn1aVZd98GkfbSs/clmKxaYezLjcOTBVUcZ/6El9AZs1q9ZAFTeF7DNhUBS3n5AYRZncd3I1UFsq5RxovmjsEY=,iv:Je+XDwQd+jbWkoBc6MEEdlH2l4EVnDDNRiPBmPgioN4=,tag:rPA6c5d5S1j+6x1fPah2eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
