apiVersion: v1
kind: Secret
metadata:
    name: zomboid-secrets
    namespace: zomboid
type: Opaque
stringData:
    #ENC[AES256_GCM,data:pnS7w7kt2XStH7c74OuMH8wSI5plEb1k/BN9gTaYPMH1sq5uo3mtWno6I0cJvrX1wcCXQRQUG9PFbJmC2vxBnOUqQs93FLKCFaWTmr+yzHoPRTKxjgc=,iv:YUbBx70Edr0/yP6LiUSmTurtldnHPOIMgpo7LBpwYeo=,tag:MmwGaGow6tlHe3+23OEjng==,type:comment]
    ADMINPASSWORD: ENC[AES256_GCM,data:KmKqS1OoamI=,iv:0e0rZK5GA6wLI9MqyB/dcxYXe9/TLX1zv8sIFJMHpK8=,tag:FZF7H37D6g1BFmAb9PBQBw==,type:str]
    #ENC[AES256_GCM,data:VzRYyobxZ2H/2jpDH1ddsQhY1CCZNZpAzG5cB3+SVA==,iv:rxi0B2V9z1ggX6SupfZhJH9JK77UIbD/o4FpJMULpYE=,tag:rb+AdpqjLFGoCi9gCC78mw==,type:comment]
    ADMINUSERNAME: ENC[AES256_GCM,data:jerCKrs=,iv:ApprZKrZSR58l4PUOEluq4AaeiyS07/h/ZmzWsZWERA=,tag:lOUTt4fU8rgKEhQN+O7BIQ==,type:str]
    #ENC[AES256_GCM,data:o05GoYFk9IPa61DfEhzHOKXgPoEMsR+bC3cqsmf5,iv:aXFCd45mDPn+mofSPXH9Wl4gm9gMQJX5gEwxFmCUr+4=,tag:WCzbBlXFuQQYHUnPVPHxYw==,type:comment]
    PASSWORD: ""
    #ENC[AES256_GCM,data:VltY1aLDuQ3dtLyerCy6v43/H74en0q29V2I/XPW2PZwFBzmZ1L4WwrO,iv:p6TnYbLOtq3yqE+ZS2b5Tb1Pwhkhy6GAKP7LdzScPRo=,tag:BeT6xNnYByYvOK0qy4XugQ==,type:comment]
    RCONPASSWORD: ENC[AES256_GCM,data:Ns+9j6FkaOo=,iv:AGIg5cfW40XkmPVv+EGKfx5E72NPe1IYFcrChdVd9K8=,tag:q8Bbprk2cthFAGldelebiw==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWEtWdVhWSTBoNEp4OXA3
            bEVPQU1RY1Z3WGExM2FYY3g2MDNGV05zZ1JnClVhTnhhdnhQZitLNzZMZjNWb2ps
            ZE15WHZKWGMwQ2ljb05FRVNqaVU3QkUKLS0tIEtCTWUwMXQ1NlNZR203dW1iSFBF
            SXhydFJUaWdYWjJYTU1ab096VEkyYk0Kd8IV5QMZqQrrVfwZyu3MSfacNMVMvkpf
            4XebAC3LuAJ32HMTQOTKulte2li44DnDmd8kpXAfIbOcCn9BO3RBCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T05:10:32Z"
    mac: ENC[AES256_GCM,data:gova9tpubUd8ShR17itsKbb8ZCpDMvpOPjX8Jmh0LnzUjM6VYfqAXV25WItAQOm8NuN4eWmZzcpZnt70DZSYJ6UT8Re2UV3jZgtdOh22EtLZgCTR+IWWHaDK/VTsWbr5/tFiu8ceZxgpuZC2FPsFq6ZLFrJoNL2LtzUaJkThbLU=,iv:eZEwych/L+bKfmYhbH6IEAmklle2Nxcus2yE7JvCU1g=,tag:XHYPXES/guIhCflbAdaeiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
