---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./viewer.serviceaccount.yaml
  - ./viewer.clusterrolebinding.yaml
  - ./httproute.yaml
  - ./oidc.externalsecret.yaml
  - ./securitypolicy-oidc.yaml
