---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: weave-gitops
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.0.36
    digest: sha256:7962f594c278045646e5d0c51498d4981a295ecda8e340c3f106d63505bdf828
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
