---
apiVersion: v1
kind: Namespace
metadata:
  name: drawio
  labels:
    webgrip.io/owner: platform
    webgrip.io/tier: app
    webgrip.io/exposure: internal
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
