---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bluemap-config
data:
  core.conf: |
    # Managed by GitOps (homelab-cluster).
    #
    # Setting accept-download=true indicates you accept Mojang's EULA and
    # confirm you own a Minecraft: Java Edition license. BlueMap will download
    # required client resources from Mojang to render maps.
    accept-download: true

  webserver.conf: |
    # Managed by GitOps (homelab-cluster).
    enabled: true
    webroot: "bluemap/web"
    port: 8100
