---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./configmap.yaml
  - ./configmap-frontend.yaml
  - ./sparkyfitness-secrets.externalsecret.yaml
  - ./sparkyfitness-secrets.pushsecret.yaml
  - ./sparkyfitness-db-secret.externalsecret.yaml
  - ./sparkyfitness-db-secret.pushsecret.yaml
  - ./database
  - ./ocirepository.yaml
  - ./helmrelease.yaml
