---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: invoiceninja
  namespace: invoiceninja
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: invoiceninja-mariadb
  namespace: invoiceninja
automountServiceAccountToken: false
