---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pyroscope
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.3
    digest: sha256:fdbba70a429ec0c50f819d76b4d6a288dcccb5bf0165b8108c94b9f2195aebe1
  url: oci://harbor.webgrip.dev/ghcr/grafana/helm-charts/pyroscope
