---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pyroscope
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.1
    digest: sha256:51859560888c54ca415d43f438d93e1c5f0b9aa2fbedf2e41655df50f692f793
  url: oci://ghcr.io/grafana/helm-charts/pyroscope
