---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudflare-dns
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.21.1
    digest: sha256:b01b4641f173e6f432e7186775722bb09261842b4a121357af37df87b33b1e27
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
