---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: erfbeeld
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/erfbeeld
  ref:
    tag: 0.1.0
    digest: sha256:6b4a401679edfe0ead2c1fe385bf9441976db776e3b412cdaacaa65a36798b6d
