---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: erfbeeld
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/nuala-nalatenschap/erfbeeld
  secretRef:
    name: harbor-pull
  ref:
    tag: 1.0.3
    digest: sha256:68c21227b8c24539466ff9ffd4bbe53635a2aaa58432e9b91ed4b34c6c420b2f
