---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./redis.yaml
  - ./httproute.yaml
  - ./clustersecretstore.yaml
  - ./infisical-app-secret.sops.yaml # step A — before wiring in (required to boot)
  #   - ./eso-auth.sops.yaml               # step B — after creating the machine identity
