---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: de-vloer-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: de-vloer
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: de-vloer-workspaces
      ports:
        - protocol: TCP
          port: 4080
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: de-vloer-api
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: de-vloer
  egress:
    - toEntities:
        - kube-apiserver
