---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: de-vloer
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/de-vloer
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.5
    digest: sha256:32b172cacb2176f1cfbfa9c0be061e8feb23ec445f7af2cb373e7bf6a73ee384
