---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: de-vloer
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/de-vloer
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.30
    digest: sha256:ddb9be60b8420301ecdc068a70244f6a14fc2e5f289af2809faf2f5fcbc2be38
