---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: de-vloer
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/de-vloer
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.2
    digest: sha256:1e0d53afd3b7947d59cf38e52a347bd85278d807f3eb7120bf157727301ff73b
