---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: observability
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 30.0.0
    digest: sha256:67cf2b33ce97df4fec11e16f2d91a1d1969fc8de5ef480fa743f20ce30f06095
  url: oci://harbor.webgrip.dev/ghcr/prometheus-community/charts/prometheus-operator-crds
