---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-google
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: litellm-google
    creationPolicy: Owner
  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: google/litellm
        property: GEMINI_API_KEY
