---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.13.0
    digest: sha256:90faa24f33edb6483fc7de109db26e9e9dd1734a5a85abe24f7e5a184fda594b
  url: oci://ghcr.io/home-operations/charts-mirror/metrics-server
