---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.50.0
    digest: sha256:30693bb721871eaf9ca35bd7c9364b774783e5cf564c55450e8cf0552721a618
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
