---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.18.6
    digest: sha256:110fc7fb0f4f8dda7751b76cb1f528292d51d6f1711c2487d1aa14a237e6ad4a
  url: oci://ghcr.io/home-operations/charts-mirror/cilium
