---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./serviceaccount.yaml
  - ./harbor-pull.externalsecret.yaml
  - ./upstream-token.externalsecret.yaml
  - ./oidc.externalsecret.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./securitypolicy-oidc.yaml
  - ./networkpolicy.yaml
components:
  - ../../../../components/placement/worker-pool
