---
apiVersion: v1
kind: Secret
metadata:
  name: guac-secrets
  namespace: security
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:ejQR7w==,iv:ZwJ6L0hipdTsypYqnZhpWffbfGgBEXzB1jfUac/uBNU=,tag:xoxOfErFMbcxTTXES7TPsw==,type:str]
  password: ENC[AES256_GCM,data:6SfSRvRtS+WsvrCEG18TutzyorCUz7bSOhwXzGbUe21AwBroL7gCByHl+3E=,iv:/dbPvpZsX33dc9Z1s7U4ZmMGTNnZdcIobkovqJuvRnE=,tag:66zVhWYLvNxYt95zLVWZhA==,type:str]
  values.yaml: ENC[AES256_GCM,data:PSiTruMlAFRJCm8S8lVjMYue0IOJj4kOvTrCO1wXSxrBq6OXk+tOJCi4RrqYkhGgg4HTPnAmX7JV/uRnbakL4491lMyTI6Q85lXxkgbTspAdEA927HLIWtbwZSnTVSDB7OUH3Cyb98VjX8Mc31Cbd8WdGi/pwj8ICrSnORqzDQ1SZmy6w/RbHWOEKOLuqr77H13t/hda7/5u3cseOHCUP+DiF3/XEJWoKspgfpvq,iv:LyAhBKaqb0gdXytNC3Y0eQD1+bu+zyfoIV1/GlW2yqc=,tag:XH1nVqi/EGFp4bdnGGjhgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM2dXemczcUFnekFBdjBy
        ZVdsZlB0bVZLRXpza0oxcmhSVkVNdEMyM0QwCnI1R3YrMXEyU3BGT1lMVzAvRWRC
        bFZjY2lXYnBtNVlwazhoTkg5dEV2MDAKLS0tIHpJSWlteGt2Y0RPTkcyV3pvZ2kz
        YmRRZHRBeExvK3dZME9UekpFSmtqZUUKbczO5QLEYfXILAVjD4bu8Y83HL2VAkSV
        hLsnAz4ZXCSANv72HC7jYCpv53aS6lHGjzTcQxSvPLA19Lx2GYGbTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T18:58:03Z"
  mac: ENC[AES256_GCM,data:zlmeJI+SakWCTTr8DiefKXpVfsjKDwvYps6XrmFOHNRobEexMMSyZdBjgI5/XrTLYVy7VOrvyB0ZPIUHJ2e6+IxsmUpGHlb5cGLa9yJ4i17PzvxV8UzRSwtoaItg5lxhh4Sp2AILDkM8ySa5xF7u++U5JD9OtczRS4bRzG59aik=,iv:iF1kO90dPXElPne1B2qc8UI9K5wDISMSf3T7KYah110=,tag:Wlmzpeh3fm8XaVw+4k+aaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
