---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - cluster.yaml
  - guac-db-backup-cronjob.yaml
  - guac-secrets.externalsecret.yaml
  - guac-secrets.pushsecret.yaml
components:
  - ../../../../../components/security-s3
