---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:pxduY/e/uOlfCfjS9gNf5DP9IRMeEe0q/POME80G6B52ouYqp2U9kQ==,iv:jmgzmXACuYZGFxBDB2gqvuIHyTWI84ecWpkvIuw0wxQ=,tag:dmUjcsGSMkk4f6BqUjQu9A==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:x2xjs3usJ6qeZnH4x+IWD3X9dfLGkN36zHJ1Gy6IZAAJxLUuqXW4yfXJ+yj0VsmCo8c2MExciTl5jYKsq0UEB+Rw7dipguswqHsFmMlNu0msvcvmUFd25QxWEaIfVBZFuy7MWUm+z266nHKjlTlQGDG/3G4HYSNo7JUfkP2rqnU=,iv:sdmb7SPF7AIn5d2AviRM+/mDbXnQboWNacPMyKnS47g=,tag:eYgkGCI3DfwrYTApmUd3dQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVXA4MStUUGZINmpIbjh4
        dGtKL3d1WVFLZkdrUmQ4OUpwcTkyem9pZEUwCi96VEhiM0p5MkcvTnhMcDVhcENF
        SGRpNzluMGJVTlU5dFI0T2luYXpHUkUKLS0tIHUwRUdLNGZ4cDNxcCtuZG4rR1lu
        bzJpblZlRE5jd2JEcUJQSzFFbHZKdjQKroUzmWLixepydJohbdL1+vD3nq1kyaSL
        TiFRr+5a74BQxqeWnWuMZz2EvQW1p0YTJUJc1t80AY2Na4Dg//RywA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-06T10:18:32Z"
  mac: ENC[AES256_GCM,data:Y0mX5XQw3Tnto+er8/RTZMfVodBB8DC/yB5fQgkR2R2ZjdKLmOnXIfZWQLK29UDmbCPQEjB7fZGQpOxopVtBMJX+2WFKgL+0SHrxsGVKtSs6TzKgTN4pplWQthtVYV9KvppMODIGY1ZT4+W6yEeAmUq0GQCYuDrWP5HX7OFkzpI=,iv:5q5+jUmuwnjd6e9I0h3R5ZNSB4YJ3ViY2vcIt6XXfZs=,tag:xz6kavyDbhSh3lupZ05cPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
