apiVersion: v1
kind: Secret
metadata:
  name: grafana-github-api
  namespace: observability
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:Fn7+bs/faG95dGZhzXDKYc5tw0ufi1WFDj4rcEVFq9OjSj4L4mGs3zlsn0iQZcLjisw0pd6F9d5LWREFVY0z8+bnH62aipiihZkg26p9wfFmdl+cM3jPdq3gvOb6,iv:/7Agqj5LvMWwxdZOAlW3dO/A51fdnYr7/XHvl7xpNcc=,tag:1AC3Vc5hTlyBwk/UAMG8EA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NnU1L0dUZEFFRytjZkh2
        VHBjSURCNi9CK2ZDR2lmUkkyMXBUK3J0SVNjCjRFZzRJeHRNYTJEU2ZJeDU2dURu
        OFlpVjhBVTdpUzhQdHNjbjc0Y0NhSGsKLS0tIFV5NVN4UlIvNXZuNHozVmZRSitM
        Qi9NZndXa2N4bGFmSDQvdTZxWnFWNVEKcU0bk7NQK8K494lfykvDjL7LJZtlCZKt
        /fDdEp9auFhbit8MkqkJAcE9Zqve3A60qaXza1UtXDfNXRSze8Qa+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-22T09:17:59Z"
  mac: ENC[AES256_GCM,data:8Mic/CfrwXpAyGAS/r2SNZJ2y2R80dgmXqW9oah5mvtDgsMkXoAKROFi0gJzS17gJz8rCSfArhNj2AhKWAikSxOuelpCUzqurpjKn4TwAjSMDn2c9v/TKpa+mNdJjqwzps2aHoTUMtYi+v3Oy4wF9tFyIa0JJA/9Me39A/ksFgU=,iv:/mup5HVZb787A2hnmnNrdrgZ0HI0uXphppRn+X7B1p4=,tag:00CS1nFT3paRb8EPBgiPkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
