apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-secret
    namespace: observability
stringData:
    username: ENC[AES256_GCM,data:9jqkqmJVRQ==,iv:T2GAr/7UmzGQeHgX/TSBD/W9gABsmpMsKBmftnCBrGY=,tag:z4sEkzKYrgtYPhjsHTPWgQ==,type:str]
    password: ENC[AES256_GCM,data:n8Y4MRzOZ09cbzljBw+Y7UgzE5+bZK7Y6dGJ2BPyVT2QZDSpGcC8Dqbq2AQ=,iv:GAlJixEliei3xtY6RyfgNCIp3gaoSfgynqM6MpXMkzA=,tag:WQq745qhppKTOlt4yPL/fA==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWFoQU5ybEU4eDJ5Sk03
            Qy9HTmhBazZoNHZYUmI2aUtxV1NaVkhFeUJVCkovMVVKVTdmdm5rUXdELzNrNU1a
            MVFyZmJTWDUrV1Z5ZXN5TW5tb3JOdEEKLS0tIFYwcW5ycTRabjBqMjZFTTg4S0I5
            VVZEVFpZN2p3Z1FBLzZ4Yk9xY1MxTFUKSUp3LBskbASNcPgJN1+to16IEuQMVY+J
            qMOSpHvozbvuZOfCx3Rt3yNYfnLQNYAm/8Yx9l8NYlDdRFjgMTpQyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T15:55:57Z"
    mac: ENC[AES256_GCM,data:XdXYT4gK3KtsVmiQgw2/apJSD/HaxwQSVIc65qC0Ldtd/SZYJ0TUjGGLS0jHFdSMB5GKhYETFzaMj4pc8PQ+XSdqDa6G5iMWrrO5zGM/UDbuVqbbCRXZDkTts21f2Z5Yz6g8ILauNch7MALZkoFop8X/iFuwi0bZZmFPjo9Mo3M=,iv:pwlV9DYURAvzYOJcv/T6elrhSFou3gxSwgZs/zFQMmc=,tag:75XdTvUD0dHrTQqP+xQJ4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.13.1
