---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-github-oauth
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:UcajdIW6yThbN+LGU9001Y9WE04=,iv:D0PDUtuEuEYPXzqXbJmgKCJWFNT2cwUQTVrIh5QOX4w=,tag:K3EB1i8b3lXsxzTlj11L2g==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qprdZhYpaS6cJF/1adRPqHg=,iv:Ay3eifhRM7eLZrqr/SdZZICy6zKBXftMig3MKjp9AVI=,tag:fmU4/5buaRsBew2SwASYWA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVXA4MStUUGZINmpIbjh4
        dGtKL3d1WVFLZkdrUmQ4OUpwcTkyem9pZEUwCi96VEhiM0p5MkcvTnhMcDVhcENF
        SGRpNzluMGJVTlU5dFI0T2luYXpHUkUKLS0tIHUwRUdLNGZ4cDNxcCtuZG4rR1lu
        bzJpblZlRE5jd2JEcUJQSzFFbHZKdjQKroUzmWLixepydJohbdL1+vD3nq1kyaSL
        TiFRr+5a74BQxqeWnWuMZz2EvQW1p0YTJUJc1t80AY2Na4Dg//RywA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-06T06:20:56Z"
  mac: ENC[AES256_GCM,data:8NmGBy9mut+I8EhGvVzhxAHQbv7LpPlmbEDJr51YuOLCaWOYbXnpvJCh1TPqQQFLY77v5zEGpDifQgfIx39zJKEdloJgPl0TTy4wA+HxIckSnOjqaV/DyZVCfadOUhI9b7C2cFjQIK2a7OPVaKMZbBl1LMIYpYLI0qJJKoJ0iXE=,iv:pFbjUhGnOaBlaLoSTKq8PszPTIZ8NPIs1ajzNTRmTUU=,tag:sIAAnuQ/hRnovBWPz30klw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
