---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - {kind: ClusterSecretStore, name: openbao-push}
  selector: {secret: {name: renovate-secrets}}
  data:
    - match: {secretKey: RENOVATE_DOCKERHUB_TOKEN, remoteRef: {remoteKey: renovate/operator, property: RENOVATE_DOCKERHUB_TOKEN}}
    - match: {secretKey: RENOVATE_DOCKERHUB_USERNAME, remoteRef: {remoteKey: renovate/operator, property: RENOVATE_DOCKERHUB_USERNAME}}
    - match: {secretKey: RENOVATE_GITHUB_APP_ID, remoteRef: {remoteKey: renovate/operator, property: RENOVATE_GITHUB_APP_ID}}
    - match: {secretKey: RENOVATE_GITHUB_APP_INSTALLATION_ID, remoteRef: {remoteKey: renovate/operator, property: RENOVATE_GITHUB_APP_INSTALLATION_ID}}
    - match: {secretKey: RENOVATE_GITHUB_APP_PRIVATE_KEY, remoteRef: {remoteKey: renovate/operator, property: RENOVATE_GITHUB_APP_PRIVATE_KEY}}
