---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
      name: ".+-db"
    patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: not-used
      spec:
        imageCatalogRef:
          apiGroup: postgresql.cnpg.io
          kind: ClusterImageCatalog
          name: postgresql
          major: 18
