---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-alloy-gateway-otlp
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: http_alloy_otlp_gateway
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://envoy-internal.network.svc.cluster.local/v1/traces
      labels:
        endpoint: alloy-gateway-otlp
        synthetic: route
