---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-harbor
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: http_harbor_gateway
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://envoy-internal.network.svc.cluster.local/api/v2.0/health
      labels:
        endpoint: harbor
        synthetic: route
