---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.0.1
    digest: sha256:9e9309a5027e3cb92149909733cd2bb6a229a2e6780c27e79091ccbb601e5a3b
  url: oci://ghcr.io/grafana-community/helm-charts/loki
