---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 17.0.1
    digest: sha256:8c293b1869de643ff815f566585ff3cf289b9eb1c4335dfdcaf2ea9e2d1ed6ea
  url: oci://ghcr.io/grafana-community/helm-charts/loki
