---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.1.1
    digest: sha256:8442ea12db07c746adc6bdbc2d8a2225abe5847b46041049bdd320bb8583f570
  url: oci://ghcr.io/grafana-community/helm-charts/loki
