---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../model
  - ./serviceaccount.yaml
  - ./rbac.yaml
  - ./clusterrole-reader.yaml
  - ./clusterrole-operator.yaml
  - ./networkpolicy.yaml
  - ./terraform-broker.yaml
  - ./terraform-kubernetes.yaml
