---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
spec:
  instances: 1
  inheritedMetadata:
    annotations:
      reloader.stakater.com/auto: "true"
  storage:
    size: 10Gi
    storageClass: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: n8n-db-store
        serverName: n8n-db
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-secret
