---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-db-daily
  namespace: n8n
spec:
  schedule: "0 15 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: n8n-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
