---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.1
    digest: sha256:9fa5d73119d55fd9cf3ef426ebb23b1c00a9efd1983cc643e6afb879cfc4c0a5
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
