---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterissuer.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./cert-manager-secret.externalsecret.yaml
  - ./cert-manager-secret.pushsecret.yaml
