---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:5WRW+Bwf+3yEdpHfI6I7JbNLJHi/QhJTtoK56CiMEyeZwgcmTE33+hqOLrvbmixPzYH4Oup+iQbYzf6krc2rhC4um7vt1TuTxgggLRVMEDI=,iv:vkhCDUVX3c8WHK575ZU9/Trx7RKbsJSoy4tr68wIyvg=,tag:PsgZnUhq5TXsupgGwc1ALA==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD_HASH: ENC[AES256_GCM,data:Qg7XYYym6MQgS1ls9qpxcIBJQb0ll+lpsfwYcxHabAUs2bcqkV2pKozRNhk2M6q0STXn7gfUina4tjjzdaDMFA==,iv:1/cpgLdGe8Bw5XuNW1hstUg4wbA1EhTjgjxNpuSyB3I=,tag:lTKZHER3+BCER3FuUAZp1g==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:N5LKA7IWjc3d6uRANj+2xjNkW+EoiU//DRO6VkcijDuhT689aeFPJ19095+xZkOjqhY/MUr+aCV86RFzjacGWw==,iv:hzbhmydN3jCG3pFTwbNLrb7jmnrYwPwjqoWPlUCr/nc=,tag:ke7FQJ7B1CKn+IuGaGUFQQ==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:MGUtWWnc2YCnAbzWUNEb6no3i3jh,iv:fIB1wC8Tv3yGjjvRIFG0NHPVomB2dLD9cETkEVzqAGQ=,tag:wXIcPNdqfKObCazKrYXAZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cFpnbWNuWjRTU1FEOUk4
        OG5XM2NKWmU0UVB3V1ZjTnFreW9Lc3V3WndzCnZrNEpSNTd0TWlkVitwSDZ6NzUy
        a0dGb054MW5OTHROK1BPTzJHRHZhQ2sKLS0tIGI1NDRXNndHR0lHVEp3T1ExYXMw
        WHZDV0tYMk5qbmdEcTVESGRzOEV1NTAKO1O19iS8fr4nNiXieTDPesjKflM52gqj
        sxZvL4rmP4NRAV0RfAdZmxhkq+OCOYgAOFQaU4QcV+4cj9GixeNg/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T05:10:22Z"
  mac: ENC[AES256_GCM,data:t7RyRSi6vOgqIBCHjxLWmIFXZiyuGck8Gt0zDdWqcT5fNP84hnWmuZE1uew+Zxyszl3hDCXVH3K/bVjTqt2Tzo2RL52JPfGQxX9COD6CCo5PE/4KQ4D5la9DHgwWVjkcWppOgEvn1xkDHzTruLEJ6XW4hChmAkbLE7QPZJRm8mM=,iv:qxofCqA2iwdz202fg5bCH34cpT89kvMZGZ1FV/7rN+Q=,tag:ctR25BzVFXKg9B6UQwLlqA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
