---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudflare-access-oidc-client
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: openbao-push
  selector:
    secret:
      name: cloudflare-access-oidc-client
  data:
    - match: {secretKey: CLOUDFLARE_ACCESS_OIDC_CLIENT_SECRET, remoteRef: {remoteKey: cloudflare/access-oidc, property: client_secret}}
