---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./authentik-secret.externalsecret.yaml
  - ./authentik-secret.pushsecret.yaml
  - ./harbor-oidc-client.externalsecret.yaml
  - ./harbor-oidc-client.pushsecret.yaml
  - ./vikunja-oidc-client.externalsecret.yaml
  - ./vikunja-oidc-client.pushsecret.yaml
  - ./openbao-rbac.yaml
  - ./networkpolicy.yaml

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/00-core-groups-users.yaml
      - blueprints/10-policies.yaml
      - blueprints/20-flows-mfa-auth.yaml
      - blueprints/30-oidc-grafana.yaml
      - blueprints/33-oidc-backstage.yaml
      - blueprints/34-oidc-forgejo.yaml
      - blueprints/35-oidc-openbao.yaml
      - blueprints/36-oidc-harbor.yaml
      - blueprints/37-oidc-vikunja.yaml

generatorOptions:
  disableNameSuffixHash: true
