---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./pvc.yaml
  - ./serviceaccount.yaml
  - ./helmrelease.yaml
  - ./authentik-secret.externalsecret.yaml
  - ./authentik-secret.pushsecret.yaml
  - ./harbor-oidc-client.externalsecret.yaml
  - ./harbor-oidc-client.pushsecret.yaml
  - ./vikunja-oidc-client.externalsecret.yaml
  - ./vikunja-oidc-client.pushsecret.yaml
  - ./litellm-oidc-client.externalsecret.yaml
  - ./litellm-oidc-client.pushsecret.yaml
  - ./cloudflare-access-oidc-client.externalsecret.yaml
  - ./cloudflare-access-oidc-client.pushsecret.yaml
  - ./longhorn-oidc-client.externalsecret.yaml
  - ./longhorn-oidc-client.pushsecret.yaml
  - ./dashboards-oidc-client.externalsecret.yaml
  - ./dashboards-oidc-client.pushsecret.yaml
  - ./networkpolicy.yaml

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/20-flows-mfa-auth.yaml

generatorOptions:
  disableNameSuffixHash: true
