---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: open-webui-oidc-client
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: openbao-push
  selector:
    secret:
      name: open-webui-oidc-client
  data:
    - match: {secretKey: client_secret, remoteRef: {remoteKey: authentik/open-webui-oidc, property: client_secret}}
