---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./harbor-pull.externalsecret.yaml
  - ./webhook-secret.externalsecret.yaml
  - ./agent-builder-token.externalsecret.yaml
  - ./agent-litellm-master.externalsecret.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./database
