---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ploeg
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/ghcr/ploeg-hq/charts/ploeg
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.2.0-rc.12
    digest: sha256:efc5f42ea8db59dc5c83864cdfe61678af19d3b47f67492e062cd0bb6e2a0d5b
