---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ploeg
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/ghcr/ploeg-hq/charts/ploeg
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.2.0-rc.8
    digest: sha256:072cb3bbd237dc81926b4a7038e2ce89b0766962bd08726f5394b907456c8713
