---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ploeg
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/ploeg
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.27
    digest: sha256:ab299879eed3b574301f595089d8ab15b5f94d8389e9fc9f698885d3b1e76bbb
