---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudflare-dns-tokens
  namespace: forgejo
spec:
  refreshInterval: 10m
  secretStoreRefs:
    - {kind: ClusterSecretStore, name: openbao-push}
  selector: {secret: {name: cloudflare-dns-tokens}}
  data:
    - match: {secretKey: unfoldhq-dev-ro, remoteRef: {remoteKey: cloudflare/dns/unfoldhq-dev-ro, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/unfoldhq-dev-ro, property: account_id}}
    - match: {secretKey: unfoldhq-dev-rw, remoteRef: {remoteKey: cloudflare/dns/unfoldhq-dev-rw, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/unfoldhq-dev-rw, property: account_id}}
    - match: {secretKey: twente-dev-ro, remoteRef: {remoteKey: cloudflare/dns/twente-dev-ro, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/twente-dev-ro, property: account_id}}
    - match: {secretKey: twente-dev-rw, remoteRef: {remoteKey: cloudflare/dns/twente-dev-rw, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/twente-dev-rw, property: account_id}}
    - match: {secretKey: webgrip-nl-ro, remoteRef: {remoteKey: cloudflare/dns/webgrip-nl-ro, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/webgrip-nl-ro, property: account_id}}
    - match: {secretKey: webgrip-nl-rw, remoteRef: {remoteKey: cloudflare/dns/webgrip-nl-rw, property: token}}
    - match: {secretKey: account-id, remoteRef: {remoteKey: cloudflare/dns/webgrip-nl-rw, property: account_id}}
