---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./exception-helmrepositories.yaml
  - ./exception-system-certs.yaml
  - ./exception-cnpg-pods.yaml
  - ./exception-envoy-gateway.yaml
  - ./exception-third-party-workloads.yaml
  - ./exception-third-party-images.yaml
  - ./exception-arc-runners.yaml
  - ./exception-forgejo-runner.yaml
  - ./exception-forgejo-agent-runner.yaml
  - ./exception-forgejo-dind.yaml
  - ./exception-forgejo-buildkitd.yaml
  - ./exception-ploeg-worker.yaml
  - ./exception-prometheus-rulefiles.yaml
  - ./exception-flux-bootstrap.yaml
  - ./exception-third-party-pods-base.yaml
  - ./exception-third-party-images-pods-base.yaml
  - ./exception-kepler.yaml
  - ./exception-guac-db-backup-tier.yaml
