---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.8.0
    digest: sha256:828b0bf1dd0a8312665590802d7e3d0d360560d44ac8afd9f4ce6ed72564c56d
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
