---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tei-embeddings-models
  namespace: ai
  labels:
    app.kubernetes.io/name: tei-embeddings
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi
