#!/usr/bin/env bash
# Deterministic docs-drift report (estate item #8, v1 — pure git, no LLM).
# Emits markdown on stdout:
#   1. DRIFT: apps whose kubernetes/apps/<ns>/<app> manifests changed in the
#      window while docs/techdocs/** did not change in the same commits — the
#      docs may no longer describe what runs.
#   2. STALE: docs pages untouched for STALE_DAYS — freshness candidates.
# Needs full git history (fetch-depth 0); a shallow clone dates everything today.
set -euo pipefail

WINDOW_DAYS="${WINDOW_DAYS:-7}"
STALE_DAYS="${STALE_DAYS:-90}"

echo "# Docs drift report"
echo
echo "Window: manifests vs docs over the last ${WINDOW_DAYS} days · stale threshold ${STALE_DAYS} days."
echo "Generated by \`scripts/docs-drift-report.sh\` (deterministic; see the docs_drift workflow)."
echo
echo "## Manifest changes without docs changes (last ${WINDOW_DAYS} days)"
echo

drift_found=0
# App dirs touched in the window
while IFS= read -r appdir; do
  [ -n "$appdir" ] || continue
  # Did ANY commit in the window touch both this app AND docs? If no commit
  # touching the app also touched docs, flag it.
  # `|| true`: a no-match grep inside the substitution must not trip set -e —
  # it killed the whole report at the first unpaired app (caught by the
  # must-fire test before this ever shipped).
  paired=$(git log --since="${WINDOW_DAYS} days ago" --format='%H' -- "$appdir" \
    | while IFS= read -r c; do
        if git show --stat --format= "$c" -- docs/techdocs | grep -q .; then echo paired; break; fi
      done || true)
  if [ -z "$paired" ]; then
    # Pure dependency bumps aren't docs-worthy; keep the signal human.
    nonbump=$(git log --since="${WINDOW_DAYS} days ago" --format='%s' -- "$appdir" | grep -cv '^chore(container)' || true)
    if [ "$nonbump" = 0 ]; then
      bumps_only="${bumps_only:-} \`${appdir#kubernetes/apps/}\`"
      continue
    fi
    last=$(git log --since="${WINDOW_DAYS} days ago" --format='%h %ad %s' --date=short -1 -- "$appdir")
    echo "- \`$appdir\` — $last"
    drift_found=1
  fi
done < <(git log --since="${WINDOW_DAYS} days ago" --name-only --format= -- kubernetes/apps \
  | grep -oE '^kubernetes/apps/[^/]+/[^/]+/' | sed 's:/$::' | sort -u)

[ "$drift_found" = 1 ] || echo "_None — every app change in the window came with a docs change, or nothing changed._"
[ -z "${bumps_only:-}" ] || { echo; echo "_Image-bump-only changes (no docs expected):_${bumps_only}"; }

echo
echo "## Stale pages (untouched ≥ ${STALE_DAYS} days)"
echo

stale_found=0
cutoff=$(date -d "-${STALE_DAYS} days" +%s 2>/dev/null || date -v -"${STALE_DAYS}"d +%s)
while IFS= read -r f; do
  ts=$(git log -1 --format=%at -- "$f" 2>/dev/null || echo 0)
  if [ "$ts" -gt 0 ] && [ "$ts" -lt "$cutoff" ]; then
    echo "- \`${f#docs/techdocs/docs/}\` — last touched $(git log -1 --format=%ad --date=short -- "$f")"
    stale_found=1
  fi
done < <(git ls-files 'docs/techdocs/docs/**/*.md' | grep -vE 'adr-0000-template')

[ "$stale_found" = 1 ] || echo "_None — nothing older than ${STALE_DAYS} days._"
