---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: executive
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  allowCrossNamespaceImport: true
  uid: executive
  title: "Executive"
