---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: infrastructure
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  allowCrossNamespaceImport: true
  uid: infrastructure
  title: "Infrastructure"
