---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: synthetics
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  allowCrossNamespaceImport: true
  uid: d892add9-e5ce-4616-99e8-9a7c27998b34
  title: "Synthetics"
