---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: Loki
    type: loki
    uid: loki
    editable: true
    access: proxy
    url: http://loki-gateway.observability.svc.cluster.local
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id"\\s*:\\s*"([0-9a-fA-F]{32})"'
          datasourceUid: victoriatraces
          url: "$${__value.raw}"
