---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs-audit
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: VictoriaLogs Audit
    type: victoriametrics-logs-datasource
    uid: victorialogs-audit
    editable: false
    access: proxy
    url: http://vlsingle-victorialogs-audit.observability.svc.cluster.local:9428
