apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: talos-soyo-1
  namespace: homelab
  title: soyo-1
  description: Control-plane Talos node at 10.0.0.20.
  tags:
    - talos
spec:
  type: node
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    ip: 10.0.0.20
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: talos-soyo-2
  namespace: homelab
  title: soyo-2
  description: Control-plane Talos node at 10.0.0.21.
  tags:
    - talos
spec:
  type: node
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    ip: 10.0.0.21
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: talos-soyo-3
  namespace: homelab
  title: soyo-3
  description: Control-plane Talos node at 10.0.0.22.
  tags:
    - talos
spec:
  type: node
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    ip: 10.0.0.22
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cluster-api-vip
  namespace: homelab
  title: Talos API VIP
  description: Virtual IP for Talos and Kubernetes API access defined by `cluster_api_addr`.
  tags:
    - vip
spec:
  type: network-endpoint
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    address: 10.0.0.25
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-gateway-lb
  namespace: homelab
  title: k8s-gateway LoadBalancer
  description: Split-DNS listener IP served by Gateway API.
  tags:
    - dns
spec:
  type: network-endpoint
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    address: 10.0.0.26
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: envoy-internal-lb
  namespace: homelab
  title: Envoy Internal LoadBalancer
  description: LAN-only ingress VIP (`cluster_gateway_addr`).
  tags:
    - gateway
spec:
  type: network-endpoint
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    address: 10.0.0.27
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: envoy-external-lb
  namespace: homelab
  title: Envoy External / Cloudflare Tunnel
  description: External ingress VIP bridged through Cloudflare Tunnel (`cloudflare_gateway_addr`).
  tags:
    - gateway
spec:
  type: network-endpoint
  owner: group:homelab/platform-team
  system: homelab/talos-cluster
  parameters:
    address: 10.0.0.28
