---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  chartRef:
    kind: OCIRepository
    name: n8n
  interval: 30m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: uninstall
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: n8nio/n8n
              tag: 2.10.2@sha256:cfa50544c4cc172506834da1ec9bb5171db55958c8d1918205df0bda237a56f4
            envFrom:
              - configMapRef:
                  name: n8n-env
              - secretRef:
                  name: n8n-secrets
            ports:
              - name: http
                containerPort: 5678
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 80
            targetPort: http
    persistence:
      data:
        existingClaim: n8n
        advancedMounts:
          n8n:
            app:
              - path: /home/node/.n8n
                readOnly: false
