# Plaintext template for n8n secrets.
#
# SOPS policy in this repo: do NOT commit a plaintext Secret containing real values.
#
# How to use:
# 1) Fill in the placeholders below
# 2) Encrypt with SOPS (age) into: n8n-secrets.sops.yaml
# 3) Add the encrypted file to this kustomization: kubernetes/apps/n8n/n8n/app/kustomization.yaml
#
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:AgE/FQQ1wQ8ngocE8bpo2tFaT2pX4Scy6TGfXHNbnI3LYhYh3harnZGtY10/BsxuIaVH5Rk0EbnQ12/aU9Xl6RB6syNlXA==,iv:D1qeAS647Yom78U7cJrTBZSgHjxpNISdD2zTLBHBWKk=,tag:/ild+2QiwZ57cMkV+koPKQ==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:EgBU/yWSM2av/jZ746g1ZZY4jdUkA5khCXQrj2QCJYY1ET6T2RUiETlr9HU=,iv:v58A1O1ANcovda4lp2jHXbT0ezEaEmb39KJtST23iqc=,tag:fFacYa8ow9/SJM8j4WNB4g==,type:str]
    #ENC[AES256_GCM,data:hc4PJir5Sep9X4pJaENgYPGREz94R2/MOK54x8Ts+predxptTZaTCPVTGXYFeJOn,iv:LEGX8Nki0cT+DAzHIqbplBohz8WpIduZSoZrUnw0If0=,tag:XE+GxqEnadVz3kqCQMuDtg==,type:comment]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:WqYZaXIrX5wiTh7x1z7An4GlUH0=,iv:+CiiKWcs7NxHoul6vIgNJkEFoJ6pBmFE+Q+8bPWB0VI=,tag:3IwaEr/6gvpN9OQ7siryZw==,type:str]
    #ENC[AES256_GCM,data:1+6zpv86bQtbd8FFYNZKScKulQokhbt23KYb6XMi5Ek=,iv:cnpJY0N/wq3AmxePULZEv0YtlkizQv48FznXu2VGJSY=,tag:CUFgu24JGm8hOI58cPXUtg==,type:comment]
    #ENC[AES256_GCM,data:3R9ljccbYyXrfGYRb6W5YHASFWFKJPyIE2ZKKUC5h8qFNyCJF/TZnYo=,iv:QTPK3Po6gJhbWpTQNSeJXUWGLS8cVKVC3XBqB0qFaic=,tag:JrR2gNoTTfsZpoS00YkVkw==,type:comment]
    #ENC[AES256_GCM,data:XLRKRTuS2BEPl1ZuCLEjD6BOvH+ptMJsRKj5X3cKwo6W8SndlCfzZ4SEI+hEmZfkecbQU5obwUAkoXlErdMbrV0qnVnAeg==,iv:MK3tz3M4og0k01kRZFr9JANODA9cmOB7pQDwfwHxJKk=,tag:3ZxOBHsohC4VfVqQfsepWA==,type:comment]
    #ENC[AES256_GCM,data:6fvIpfXvZOuRNMfb7g5f5cBjYk64Daaoug==,iv:9JKg9wayj+B67CdCHaq9Z4OU6Ar/aO5CuuAUrdWcKf8=,tag:xmrFZtFWzD7b937a98x6Aw==,type:comment]
    #ENC[AES256_GCM,data:lHGn37BIfHfr0zc1NSg1IU4/KTycmlWCqoHj8FQnfdO2mxtXl8Y=,iv:mIUK9hHDfBnXZkSE1HUcoEE4wqi9e325jML77umENqo=,tag:N4X3MJOY72ZO5/425vZ6vg==,type:comment]
    #ENC[AES256_GCM,data:UsR25McpTPEz9eeEjhNwXprQM5kGuzyOkKEiflErmVKEpRrDl2P9WTo=,iv:E+K1G4uGXyqh5OEwil7yPGHXPwhzdSVC21MR1wNBXjU=,tag:haBSWbMe8blBAGi+qPeWQg==,type:comment]
    #ENC[AES256_GCM,data:fz1oVRI0WnRG5wUcPulSK7IFz0KwGVRx0PkprrMnK/eJsbegIEisRrQdo6s+,iv:wz4n6t5ItZmCKr12abS8xy74vHHXluDgv5BgGvZyJUg=,tag:GzUHtMV+7FXY1ieE4Az6IA==,type:comment]
    #ENC[AES256_GCM,data:Y9qrcMNE5ZzHQSlnyjpmpxVuFejH5t/mQ/TzmXT5cAVkdzn41X9H6x77,iv:KRZeofK3T0OwixZRNTCwfgZtl9FvhZcCEiUhIpzpQsQ=,tag:n2F9+0QcyYsUo8xKRoHH8Q==,type:comment]
    #ENC[AES256_GCM,data:C4T15Y3dbhbc4WrIKHf5nVITYAHQv5TIAott0gJcWqensCTP+mYNQS4rDXE=,iv:OMDqRcxuz8RTtB/x9MUHiDSTrk/AFRasesA/bA6VtXY=,tag:xLs4CafnH58wXinQUAtVIg==,type:comment]
    #ENC[AES256_GCM,data:dIQKnuzwOsrM/IcqHl2iZmUycsSC/hBsXUOJYwl1pDhuHg9KvnA=,iv:epHYdl6rnqRT9KE3eaKu4RqgwAv3MlhkXDA2Ypli/2Q=,tag:dJ9S+yaPGOC3aowEaU1CvQ==,type:comment]
    #ENC[AES256_GCM,data:zpZ2Nu62nTEpK7UVpOWsP8SXl2VQJanlQlHebWPWERCWLjHs0Hvt4A1+M0K7mEbvWQ7YrCxsllAit9vMUQ==,iv:N8bW52QFgx32Eyt2bo5KKoNHyo5stu2pQzabwRNKB4w=,tag:L5l7VT/SXHujlQeNOalojg==,type:comment]
    #ENC[AES256_GCM,data:tKljKvCxom+FlCpnQDYGsnopQ21Q6XQBUP8lI9sIRkd0TQ==,iv:GxwGHZGukuJc1R6J0A4iSZIvfgJdEzsFj8KFIGb+rKE=,tag:K+lbplQp37pzEoHs0JUehQ==,type:comment]
    #ENC[AES256_GCM,data:gGzoIT3tFjRSwQG4OSr48wGm9OZwol2UKPNcYCCaMCiVqxQ=,iv:HbcCzbq9vFr5PSiQQShkNPkEuUkieK3jf0rKiYpodRQ=,tag:M7BVZmNWwmKFfyNTVxEiyQ==,type:comment]
    #ENC[AES256_GCM,data:EtM/gjVZax0Vvawt5gJE2LjiKbN/UGcQSYf5g2HHc8T8IhYQGlidQISI+lnTac1khZ3jeuVjajB8JoZ35iwT/zKGeejztbjsDfA=,iv:QoZxnRpPRDQGoFXRqVCpw0Hcu91bSJ0vmTMtN9wBnds=,tag:D+r3xC1imyeCCv3KycQyeA==,type:comment]
    #ENC[AES256_GCM,data:k29DNwAi/tlcv9p24+wrRPX0hzpU18rEXO9SH0+2,iv:09BPyaGdQtfqFAURk5hEV1sz035cDdnCrHinR1lOBvA=,tag:SwMqKtKs3plvdHWHTSzIjg==,type:comment]
    #ENC[AES256_GCM,data:vDWZhB4eqva6ac5ySORGDiMHv0SjpFebZrFr/7c=,iv:YCcD/CZxPUAC1I07lLymDvgaUYWOJ/IjtUP7XtTZi+E=,tag:eyvhIY3c/3z2PstOnF+yLQ==,type:comment]
    #ENC[AES256_GCM,data:XY8Xmzq4VUH/O6C3JdNqApnHUSDoRluf6LUJBO/uRkAjtF4IPRzC3Q==,iv:NLfhnXD5L3R49tAvJKSR6Kv+QAWJxcrCYKlzTmrkFX8=,tag:97ncXRE6COTaxM2fLDaoZw==,type:comment]
    #ENC[AES256_GCM,data:5nUIBNBRg69o1TpbvBgOGO+fDoT6HCAbpI91LbEdKc8WwFsGrXOX+Q==,iv:gRYT+VGAXBZN550QNTg4EynkKH1VvLX9X3FkvD6S2X8=,tag:t3EpJJGxAOSQ82p7Cd81+A==,type:comment]
    #ENC[AES256_GCM,data:jLcZfk8Vb065VDrDONW6wxp8ylVxRFFPcvnlqSEJMg0aqVsZMLBE,iv:ndvmUjuK8GUgXNb6SvlOKarf39Nndm0Fyk68CsOm7zA=,tag:BgI72XD4JBtogTvMLCssWQ==,type:comment]
    #ENC[AES256_GCM,data:wW3UOt7dSEWNfkP9Noyd2vMCYDRd9zx7BKmowwNKWT8pileHQ7SWdnvGVBxqCiVG1za3xkGDgPqMTZd8SU/NQCa/A2A=,iv:6llA93MIcdJ8LAHDM17QabIXvpuxPEo8LT/7IDgyfLI=,tag:V8YJ5L4ZO8sNWVMCM8hLlQ==,type:comment]
    #ENC[AES256_GCM,data:EtpGz1CjaaD8pZMGYNP0pF1hDLlgk1qb/l8bdhuMU7mzxXe3wG1dWYr0jj+xsw==,iv:PqrdGq9y2x+VXo7dPWc6/T37wRwqSU/AC8vzjwphdNU=,tag:tRThCX5WAzmPNiGm+4VzSA==,type:comment]
    #ENC[AES256_GCM,data:GG/7lys1/T6lBQAWKMSskOw8fskmd1TR+ti9+b9mYXV2N4EM7mHSp+6cHY3Suzyrtg==,iv:AVDqSRAHrJNyyDRq9g7qKlmvZDvahjWJFEgpiep/pKA=,tag:dOFA5aPxeqwn62G9AoKogg==,type:comment]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcHVZaVoxT3M0Z1htRkQ2
            RnM1UlVMc1E5cFdWQXcvNm1DQ04zbDFpYXdBCktWbTludVlnRzdNUGQrTlE3WWVO
            ZkZPZ0ovRkpJNllZSVVnUU93TStpSFkKLS0tIHRqamQrZHZPMEV1WFhRdHpBeUI5
            ZlV2Vmd6bS8ydlNjOW83dlo5U3VPeFkK4UC6W8w3HkI/nqy1t3fZ6ClFLvVbHSk2
            pM6IbjepR++UT3n864o9p+2IAFQ70CBxTFIQKMIz5D+clp8Wk0/P7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:41:55Z"
    mac: ENC[AES256_GCM,data:dT50nD4kPVh7ppWVZJ4dt/Qa6tOOWtucgHPpBd5Xkj8smCh/fG3qT1ISSYTjqT2W9PZ1oN6+vgykT/EtlyGfxv5Lq9Jq784xv2mrRtpqe4uTSLaD6Y4SvAEoEQl27st6icz2mdp91+zLA+Fp1NwNyPqL3V4c/dbB5xh0PcQJEvA=,iv:v8HcOsGkTstBxXOkamocCV3vcysTGtnVvAzJ7VazeUg=,tag:Cewp6jpInzkxQY92he05Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
