# Plaintext template for the CloudNativePG bootstrap secret used by the n8n Postgres cluster.
#
# How to use:
# 1) Fill in the placeholders below
# 2) Encrypt with SOPS (age) into: n8n-db-secret.sops.yaml
# 3) Add the encrypted file to this kustomization: kubernetes/apps/n8n/n8n/app/kustomization.yaml
#
apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: n8n
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VWWj,iv:AjgLJB7arLI32LQVuARHiV4v1o/Jzfwu3cGIcVlpxLc=,tag:rH0+63XGSHGc2yWPlbRKwg==,type:str]
    password: ENC[AES256_GCM,data:nZS8AG04zGaXglkhCA0zyGXaX70=,iv:RSDf+00D7vKX/YX0kfAwHko/OVl5kVrO1ICP0qH3WhY=,tag:AbdJzBTbwkIw5zSA3AhrcQ==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2ptc1VmNW5TT2luZkF3
            WlFYM2JqbUZKY0dYZ09PMFkzd290UXdETFNBClJ6SjJVTWtvcy9HVEFoWVN3NDl6
            TUtIbzZMdWxPRlNoNUxKMW5nTUpRWTQKLS0tIC9yTzQraFI5RENOUnBQUk1GYlAx
            MWlkN3dMUDZjL0hSYWloWEJ1VFVFRUEKYGfRHUC5EmH2VkR0wqC/DyBWusi4n/MP
            nmm7bh4KiGV9Df+f75byrWgXW0hJWJ9ddv4vkO2hvRB6Y/HoYyZywA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:38:08Z"
    mac: ENC[AES256_GCM,data:GNunlOTUUQyJipjPIxwgxs13hH/AdwNuNFW1qHrIMgm8TtjekW5KMfUo0QBXyK2Qrc8nS0RYM/V2N5S8VFKRouDsdClcoRKvws8TfqXCVSP3fsbNx9UpkJ4Xykk7J027DCPHe+xYdsp6tNpL/ZQ1rNBGAY/o6u3TxJth/u7vHGU=,iv:/dg/0y2sKq/GJ/NL+4u8x6V0VUPsA1CT6RL7SpzTG9I=,tag:vW/wWSfS0sh3OLjFgb0EcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
