---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./register.job.yaml
  - ./networkpolicy.yaml
configMapGenerator:
  - name: omnigraph-embed-key-register
    files:
      - ./register-embed-key.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
