---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.5.3
    digest: sha256:ed154687d43d30fc54d4f6d4663b822255de96245f7d587e86d8b978317658a0
  url: oci://harbor.webgrip.dev/ghcr/prometheus-community/charts/kube-state-metrics
