---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.5.1
    digest: sha256:61cc211e4bc6fc94670a29a8b6104c96e249bbbba293db2ea37b239c539d77d4
  url: oci://harbor.webgrip.dev/ghcr/prometheus-community/charts/kube-state-metrics
