---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.6.0
    digest: sha256:86764b323431bb6d146c8e5f610abec0494272b0302114643b13039732b1a078
  url: oci://harbor.webgrip.dev/ghcr/prometheus-community/charts/kube-state-metrics
