---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kepler
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://quay.io/sustainable_computing_io/charts/kepler
  ref:
    # renovate: datasource=docker depName=quay.io/sustainable_computing_io/charts/kepler
    tag: "0.11.4"
