---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: searxng-basic-auth
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: openbao-push
  selector:
    secret:
      name: searxng-basic-auth
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: searxng/basic-auth
          property: password
