---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-basic-auth
  namespace: searxng
spec:
  refreshInterval: "0"
  target:
    name: searxng-basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        .htpasswd: "ryan:{SHA}{{ .password | sha1sum | hex2bytes | toString | b64enc }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
