---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: searxng-valkey
  labels:
    app.kubernetes.io/name: searxng-valkey
    app.kubernetes.io/part-of: searxng
automountServiceAccountToken: false
