---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    webgrip.io/owner: platform
    webgrip.io/tier: app
    webgrip.io/exposure: internal
    kyverno.io/default-network-policies: "true"
