---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
components:
  - ../../../../../components/cnpg-restore-test
resources:
  - cluster.yaml
  - objectstore.yaml
  - scheduled-backup.yaml
patches:
  - path: ./backup/restore-test/cronjob-patch.yaml
