---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: harbor-db-daily
  namespace: harbor
spec:
  schedule: "0 45 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: harbor-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
