---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config-large
  namespace: forgejo
data:
  config.yaml: |-
    log:
      level: info
    runner:
      capacity: 1
      timeout: 1h
      labels:
        - docker-large:host
    cache:
      enabled: true
      external_server: "http://forgejo-cache-server.forgejo.svc.cluster.local:8088/"
      secret_url: "file:/run/forgejo-runner/cache-secret"
    container:
      docker_host: "-"
      options: ""
      network: ""
      valid_volumes:
        - "**"
