apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homelab-cluster
  namespace: homelab
  title: Homelab Cluster Repository
  description: Flux + Talos configuration, TechDocs, and bootstrap scripts for the homelab cluster.
  annotations:
    github.com/project-slug: webgrip/homelab-cluster
    backstage.io/source-location: url:https://github.com/webgrip/homelab-cluster
    backstage.io/techdocs-ref: dir:./docs/techdocs
    backstage.io/managed-by-location: url:https://github.com/webgrip/homelab-cluster/blob/main/catalog/components/homelab-cluster.yaml
    simpleicons.org/icon-slug: kubernetes
  tags:
    - talos
    - fluxcd
  links:
    - url: https://github.com/webgrip/homelab-cluster/tree/main/docs/techdocs
      title: TechDocs Source
      icon: book
spec:
  type: platform
  owner: group:homelab/platform-team
  lifecycle: production
  system: homelab/talos-cluster
