---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unfold
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/unfold
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.56
    digest: sha256:52840418545c06ee9bf5bfb53415874dba0c3ae9243fe4f1c8677997502fec71
