---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unfold
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://harbor.webgrip.dev/webgrip/charts/unfold
  secretRef:
    name: harbor-pull
  ref:
    tag: 0.4.0-rc.42
    digest: sha256:640085bb05a04592463c5d2d9474913bd95666cdaa396c9ae5df3166f1924570
